### ISSUE TITLE
Uncaught Error: Cannot find module 'bson'

### ISSUE THREAD

**Issue by DevelHamster** [idleberg/atom-bson-converter#1]
[Enter steps to reproduce:]

1. Open any BSON file
2. Use command "BSON decode"

I've used GIT installation from README.md instructions. Atom had been restarted several times, but error is still thrown.

**Atom**: 1.28.0 x64
**Electron**: 2.0.3
**OS**: Unknown Windows version
**Thrown From**: [bson-converter](https://github.com/idleberg/atom-bson-converter) package 0.4.2

### Stack Trace

Uncaught Error: Cannot find module 'bson'

```
At module.js:545

Error: Cannot find module 'bson'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.28.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.28.0/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.28.0/resources/app/src/native-compile-cache.js:66:33)
    at Object.encode (/packages/bson-converter/lib/bson-converter.coffee:133:12)
    at /packages/bson-converter/lib/bson-converter.coffee:121:79)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.28.0/resources/app/src/command-registry.js:384:49)
    at Object.didConfirmSelection (~/AppData/Local/atom/app-1.28.0/resources/app/node_modules/command-palette/lib/command-palette-view.js:152:35)
    at SelectListView.confirmSelection (~/AppData/Local/atom/app-1.28.0/resources/app/node_modules/atom-select-list/src/select-list-view.js:401:26)
    at SelectListView.didClickItem (~/AppData/Local/atom/app-1.28.0/resources/app/node_modules/atom-select-list/src/select-list-view.js:287:16)
    at ListItemView.onclick (~/AppData/Local/atom/app-1.28.0/resources/app/node_modules/atom-select-list/src/select-list-view.js:222:37)
    at ListItemView.didClick (~/AppData/Local/atom/app-1.28.0/resources/app/node_modules/atom-select-list/src/select-list-view.js:449:16)
```

### Commands

```
     -2:40.3.0 application:open-file (atom-pane.pane.active)
     -1:21.9.0 command-palette:toggle (input.hidden-input)
     -1:16.7.0 BSON:decode (input.hidden-input)
     -0:47.6.0 core:select-all (input.hidden-input)
     -0:44.7.0 command-palette:toggle (input.hidden-input)
     -0:41.2.0 BSON:encode (input.hidden-input)
```

### Non-Core Packages

```
bson-converter 0.4.2 
```

**Comment by idleberg** [comment]
You need to install dependencies (see updated README)
